panda:                    #useful if you use a namespace for the robot
    panda_finger1_controller:
        type: effort_controllers/JointPositionController
        joint: panda_finger_joint1
        pid: { p: 100000, d: 10.0, i: 0, i_clamp: 1 }
    panda_finger2_controller:
        type: effort_controllers/JointPositionController
        joint: panda_finger_joint2
        pid: { p: 100000, d: 20.0, i: 0, i_clamp: 1 }