gripper:                    #useful if you use a namespace for the robot
    # Publish -ns:joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    r_finger_effort:
        type: effort_controllers/JointEffortController
        joint: J1
        pid: {p: 10, d: 0.1, i: 0}
    l_finger_effort:
        type: effort_controllers/JointEffortController
        joint: J2
        pid: {p: 10, d: 0.1, i: 0}

    r_finger_position:
        type: effort_controllers/JointPositionController
        joint: J1
        pid: {p: 10, d: 0.1, i: 0}
    l_finger_position:
        type: effort_controllers/JointPositionController
        joint: J2
        pid: {p: 10, d: 0.1, i: 0}
